### PR TITLE
fix highlighting in safari

### LINKED ISSUE #6: Syntax highlighting broken on iOS
Just noted that the syntax highlighting doesn’t work on my phone, not sure whether this only applies to iOS

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR attempts to fix #6, however for some reason `highlight.js` works a bit differently in Safari and does not highlight all parts of the code. Not sure why.

### CODE REVIEW

**Comment by bartvanerp** [comment]
Nice! Did you minify the original version of `highlight.js` or one from the internet? Asking this because I had included a custom version for proper `Julia` syntaxing. (https://fredrikekre.se/posts/highlight-julia/)

**Comment by bvdmitri** [comment]
@bartvanerp I got it from here https://highlightjs.org/download/. Scroll down a bit and you will have an option to select only several languages (I picked Julia & Julia REPL).

**Comment by bartvanerp** [comment]
The file I mentioned is still different though (took me half a day to figure out). `highlight.js`'s support for `Julia` is not great, otherwise we could have simply used it form out-of-the-box Hugo. Furthermore I added some extra lines to highlight common operators, such as `~`.

**Comment by bvdmitri** [comment]
@bartvanerp Ah, I didn't know you have used the modified version..

**Review by bartvanerp — APPROVED** [review]

**Pull request merged**
